local helper = require("tests.helper")

describe("SettingsUI", function()
    local ns, state, UI
    before_each(function()
        state = helper.installWowStubs()
        ns = helper.loadAddon()
        UI = ns.SettingsUI
        ns.Core.OnEvent(nil, "ADDON_LOADED", "Atlasium")
        ns.Core.OnEvent(nil, "PLAYER_LOGIN")
    end)

    it("registers one Interface Options panel and creates the native window lazily", function()
        assert.equals(1, #state.categories)
        assert.equals("Atlasium", UI.panel.name)
        assert.is_nil(UI.window)
        UI.RegisterPanel()
        assert.equals(1, #state.categories)
        UI.Show()
        local window = UI.window
        assert.equals("UIPanelDialogTemplate", window.template)
        assert.same({ "AtlasiumSettingsWindow" }, UISpecialFrames)
        UI.Toggle()
        assert.is_false(window:IsShown())
        UI.Toggle()
        assert.equals(window, UI.window)
        assert.is_true(window:IsShown())
    end)

    it("offers the same complete setting controls in both views", function()
        UI.Show()
        for id in pairs(ns.Settings.entries) do
            assert.is_not_nil(UI.panelView.controls[id], id)
            assert.is_not_nil(UI.windowView.controls[id], id)
        end
        assert.equals("UIPanelScrollFrameTemplate", UI.panelView.scroll.template)
        assert.equals("UIPanelScrollFrameTemplate", UI.windowView.scroll.template)
    end)

    it("synchronizes changes from either view without rerunning setters on refresh", function()
        UI.Show()
        local calls = 0
        local setEnabled = ns.FogClear.SetEnabled
        ns.FogClear.SetEnabled = function(value) calls = calls + 1; setEnabled(value) end
        local check = UI.panelView.controls.fog
        check:SetChecked(false)
        helper.runScript(check, "OnClick")
        assert.equals(1, calls)
        assert.is_false(UI.windowView.controls.fog:GetChecked())
        UI.Refresh()
        assert.equals(1, calls)
        local slider = UI.windowView.controls.maxZoom
        slider:SetValue(6.13)
        assert.equals(6.25, ns.db.mapNav.maxZoom)
        assert.equals(6.25, UI.panelView.controls.maxZoom:GetValue())
        assert.equals("Maximum world map zoom: 6.25×", slider.valueLabel:GetText())
    end)

    it("does not rewrite legacy saved numeric values when opening or refreshing", function()
        ns.db.minimap.angle = 225.75
        ns.db.mapNav.maxZoom = 18
        ns.db.mapNav.step = 1.234
        local before = ns.Util.CopyDefaults(ns.db, {})
        UI.Show()
        UI.Refresh()
        assert.same(before, ns.db)
        assert.equals("Maximum world map zoom: 18×", UI.windowView.controls.maxZoom.valueLabel:GetText())
    end)

    it("opens from bare and explicit slash commands even when the minimap button is hidden", function()
        ns.Settings.Set("button", false)
        SlashCmdList.ATLASIUM("")
        assert.is_true(UI.window:IsShown())
        UI.window:Hide()
        SlashCmdList.ATLASIUM("settings")
        assert.is_true(UI.window:IsShown())
        assert.is_false(ns.MinimapButton.frame:IsShown())
        assert.same({}, state.toggled)
        SlashCmdList.ATLASIUM("help")
        assert.equals(ns.Core.GetHelp(), state.messages[1]:match("Atlasium|r: (.*)"))
    end)

    it("refreshes both views after slash changes and dragging the button", function()
        UI.Show()
        SlashCmdList.ATLASIUM("worldmap fog off")
        assert.is_false(UI.panelView.controls.fog:GetChecked())
        assert.is_false(UI.windowView.controls.fog:GetChecked())
        state.cursor = { x = 940, y = 780 }
        local button = ns.MinimapButton.frame
        helper.runScript(button, "OnDragStart")
        helper.runScript(button, "OnUpdate", 0.01)
        helper.runScript(button, "OnDragStop")
        assert.near(90, UI.panelView.controls.angle:GetValue(), 1e-8)
        assert.near(90, UI.windowView.controls.angle:GetValue(), 1e-8)
    end)

    it("updates Portuguese text and the open minimap tooltip immediately", function()
        UI.Show()
        ns.MinimapButton.frame.GetCenter = function() return 883, 623 end
        helper.runScript(ns.MinimapButton.frame, "OnEnter")
        ns.Settings.Set("language", "ptBR")
        assert.equals("Configurações do Atlasium", UI.windowView.title:GetText())
        assert.equals("Configurações do Atlasium", UI.panelView.title:GetText())
        assert.equals("ptBR", UI.panelView.controls.language.selectedValue)
        assert.equals("Português (Brasil)", UI.panelView.controls.language.dropdownText)
        assert.equals("Português (Brasil)", UI.windowView.controls.language.dropdownText)
        assert.equals(ns.Localization.Get("buttonClick"), GameTooltip.calls.AddLine[2][1])
        SlashCmdList.ATLASIUM("worldmap fog off")
        assert.matches("worldmap fog desativado", state.messages[1])
        assert.matches("/atlasium worldmap fog on | off", state.messages[1], 1, true)
        assert.matches("comandos: /atlasium", ns.Core.GetHelp())
    end)

    it("keeps language names readable and applies each dropdown choice", function()
        UI.panelView.controls.language.initialize()
        assert.equals("English", state.dropdownButtons[1].text)
        assert.equals("Português (Brasil)", state.dropdownButtons[2].text)
        state.dropdownButtons[2].func()
        assert.equals("ptBR", ns.db.language)
        state.dropdownButtons[1].func()
        assert.equals("enUS", ns.db.language)
    end)

    it("previews RGB and inverse opacity and restores the snapshot on cancellation", function()
        UI.Show()
        UI.OpenColorPicker(UI.windowView)
        assert.is_true(ColorPickerFrame:IsShown())
        assert.equals(0, ColorPickerFrame.opacity)
        ColorPickerFrame:SetColorRGB(0.2, 0.3, 0.4)
        OpacitySliderFrame:SetValue(0.25)
        ColorPickerFrame.opacityFunc()
        assert.same({ r = 0.2, g = 0.3, b = 0.4, a = 0.75 }, ns.db.fogClear.color)
        assert.same({ n = 4, 0.2, 0.3, 0.4, 0.75 }, helper.lastCall(UI.panelView.swatch, "SetTexture"))
        local snapshot = ColorPickerFrame.previousValues
        HideUIPanel(ColorPickerFrame)
        ColorPickerFrame.cancelFunc(snapshot)
        assert.same(ns.defaults.fogClear.color, ns.db.fogClear.color)
    end)

    it("keeps picker changes on accept and leaves another owner's picker alone", function()
        UI.OpenColorPicker(UI.panelView)
        ColorPickerFrame:SetColorRGB(0.1, 0.2, 0.3)
        HideUIPanel(ColorPickerFrame)
        assert.equals(0.1, ns.db.fogClear.color.r)
        ColorPickerFrame:Show()
        local callback = function() end
        ColorPickerFrame.func = callback
        UI.OpenColorPicker(UI.panelView)
        assert.equals(callback, ColorPickerFrame.func)
    end)

    it("restores a picker preview when its settings view closes", function()
        UI.Show()
        UI.OpenColorPicker(UI.windowView)
        ColorPickerFrame:SetColorRGB(0.1, 0.2, 0.3)
        helper.runScript(UI.window, "OnHide")
        assert.is_false(ColorPickerFrame:IsShown())
        assert.same(ns.defaults.fogClear.color, ns.db.fogClear.color)
    end)

    it("keeps changes after Interface Options cancel and resets preferences from either view", function()
        ns.Settings.Set("language", "ptBR")
        ns.Settings.Set("fog", false)
        UI.panel.cancel()
        assert.is_false(ns.db.fogClear.enabled)
        UI.panel.default()
        assert.is_true(ns.db.fogClear.enabled)
        assert.equals("enUS", ns.db.language)
        UI.Show()
        ns.Settings.Set("maxZoom", 9)
        helper.runScript(UI.defaultsButton, "OnClick")
        assert.equals(4, ns.db.mapNav.maxZoom)
        helper.runScript(UI.closeButton, "OnClick")
        assert.is_false(UI.window:IsShown())
    end)

    it("scrolls within its content bounds with the mouse wheel", function()
        local scroll = UI.panelView.scroll
        scroll:SetHeight(400)
        helper.runScript(scroll, "OnMouseWheel", -1)
        assert.equals(36, scroll:GetVerticalScroll())
        helper.runScript(scroll, "OnMouseWheel", -100)
        assert.equals(scroll:GetVerticalScrollRange(), scroll:GetVerticalScroll())
        helper.runScript(scroll, "OnMouseWheel", 100)
        assert.equals(0, scroll:GetVerticalScroll())
    end)
end)
